### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Yilikal250** [franclobo/Leaderboard#3]
Hi @[franclobo](https://github.com/franclobo)

This project really looks nice.👏🏼🔥

Here's what I think you can adjust:

- [x] The live demo link is not working it would be better if you fix that.

Optional suggestions

- [x] for the background image i suggest you to use a high definition images so that it could be comfortable to the user.

**Comment by franclobo** [comment]
Thank you for your comments. I've already done the changes.
